export const imageDatabase = [
  // { set0: [
  //   { src: 'http://placehold.it/300x300' },
  //   { src: 'http://placehold.it/300x301' },
  //   { src: 'http://placehold.it/300x302' },
  //   { src: 'http://placehold.it/300x303' },
  //   { src: 'http://placehold.it/300x304' },
  // ]},
  // { set1: [
  //   { src: 'http://placehold.it/301x300' },
  //   { src: 'http://placehold.it/301x301' },
  //   { src: 'http://placehold.it/301x302' },
  //   { src: 'http://placehold.it/301x303' },
  //   { src: 'http://placehold.it/301x304' },
  // ]},  
  // { set2: [
  //   { src: 'http://placehold.it/302x300' },
  //   { src: 'http://placehold.it/302x301' },
  //   { src: 'http://placehold.it/302x302' },
  //   { src: 'http://placehold.it/302x303' },
  //   { src: 'http://placehold.it/302x304' },
  // ]},
  
  { set0: [
    { src: './assets/img/sharing-00-00.jpg' },
    { src: './assets/img/sharing-00-01.jpg' },
    { src: './assets/img/sharing-00-02.jpg' },
    { src: './assets/img/sharing-00-03.jpg' },
    { src: './assets/img/sharing-00-04.jpg' },
  ]},
  { set1: [
    { src: './assets/img/empathy-00-00.jpg' },
    { src: './assets/img/empathy-00-01.jpg' },
    { src: './assets/img/empathy-00-02.jpg' },
    { src: './assets/img/empathy-00-03.jpg' },
    { src: './assets/img/empathy-00-04.jpg' },
  ]},
  { set2: [
    { src: './assets/img/cooperating-00-00.jpg' },
    { src: './assets/img/cooperating-00-01.jpg' },
    { src: './assets/img/cooperating-00-02.jpg' },
    { src: './assets/img/cooperating-00-03.jpg' },
    { src: './assets/img/cooperating-00-04.jpg' },
  ]},
  { set3: [
    { src: './assets/img/helping-00-00.jpg' },
    { src: './assets/img/helping-00-01.jpg' },
    { src: './assets/img/helping-00-02.jpg' },
    { src: './assets/img/helping-00-03.jpg' },
    { src: './assets/img/helping-00-04.jpg' },
  ]},  
  { set4: [
    { src: './assets/img/eating-00-00.jpg' },
    { src: './assets/img/eating-00-01.jpg' },
    { src: './assets/img/eating-00-02.jpg' },
    { src: './assets/img/eating-00-03.jpg' },
    { src: './assets/img/eating-00-04.jpg' },
  ]},  
  { set5: [
    { src: './assets/img/engaging-00-00.jpg' },
    { src: './assets/img/engaging-00-01.jpg' },
    { src: './assets/img/engaging-00-02.jpg' },
    { src: './assets/img/engaging-00-03.jpg' },
    { src: './assets/img/engaging-00-04.jpg' },
  ]},  
  { set6: [
    { src: './assets/img/handshake-00-00.jpg' },
    { src: './assets/img/handshake-00-01.jpg' },
    { src: './assets/img/handshake-00-02.jpg' },
    { src: './assets/img/handshake-00-03.jpg' },
    { src: './assets/img/handshake-00-04.jpg' },
  ]}, 
  { set7: [
    { src: './assets/img/turntaking-00-00.jpg' },
    { src: './assets/img/turntaking-00-01.jpg' },
    { src: './assets/img/turntaking-00-02.jpg' },
    { src: './assets/img/turntaking-00-03.jpg' },
    { src: './assets/img/turntaking-00-04.jpg' },
  ]},
  { set8: [
    { src: './assets/img/sportsmanship-00-00.jpg' },
    { src: './assets/img/sportsmanship-00-01.jpg' },
    { src: './assets/img/sportsmanship-00-02.jpg' },
    { src: './assets/img/sportsmanship-00-03.jpg' },
    { src: './assets/img/sportsmanship-00-04.jpg' },
  ]},
  { set9: [
    { src: './assets/img/animalcare-00-00.jpg' },
    { src: './assets/img/animalcare-00-01.jpg' },
    { src: './assets/img/animalcare-00-02.jpg' },
    { src: './assets/img/animalcare-00-03.jpg' },
    { src: './assets/img/animalcare-00-04.jpg' },
  ]},
  { set10: [
    { src: './assets/img/listeningmusic-00-00.jpg' },
    { src: './assets/img/listeningmusic-00-01.jpg' },
    { src: './assets/img/listeningmusic-00-02.jpg' },
    { src: './assets/img/listeningmusic-00-03.jpg' },
    { src: './assets/img/listeningmusic-00-04.jpg' },
  ]},
  { set11: [
    { src: './assets/img/personalspace-00-00.jpg' },
    { src: './assets/img/personalspace-00-01.jpg' },
    { src: './assets/img/personalspace-00-02.jpg' },
    { src: './assets/img/personalspace-00-03.jpg' },
    { src: './assets/img/personalspace-00-04.jpg' },
  ]},
  { set12: [
    { src: './assets/img/interested-00-00.jpg' },
    { src: './assets/img/interested-00-01.jpg' },
    { src: './assets/img/interested-00-02.jpg' },
    { src: './assets/img/interested-00-03.jpg' },
    { src: './assets/img/interested-00-04.jpg' },
  ]},
  { set13: [
    { src: './assets/img/happy-00-00.jpg' },
    { src: './assets/img/happy-00-01.jpg' },
    { src: './assets/img/happy-00-02.jpg' },
    { src: './assets/img/happy-00-03.jpg' },
    { src: './assets/img/happy-00-04.jpg' },
  ]},
  { set14: [
    { src: './assets/img/teamwork-00-00.jpg' },
    { src: './assets/img/teamwork-00-01.jpg' },
    { src: './assets/img/teamwork-00-02.jpg' },
    { src: './assets/img/teamwork-00-03.jpg' },
    { src: './assets/img/teamwork-00-04.jpg' },
  ]}
];
